logger:
  level: "INFO"

storage:
  type: "sql"
  dsn: "host=postgres port=5432 user=postgres password=postgres dbname=calendar sslmode=disable"

rabbitmq:
  uri: "amqp://rabbit:password@rabbitmq:5672/"
  queueName: "calendar_notifications"
  exchangeName: "calendar_exchange"
  statusQueueName: ""
  statusRoutingKey: ""

scheduler:
  interval: "1m"
  lookAhead: "24h"
  cleanupOlder: "8760h"  # 1 year in hours