logger:
  level: "INFO"

rabbitmq:
  uri: "amqp://rabbit:password@rabbitmq:5672/"
  queueName: "calendar_notifications"
  exchangeName: "calendar_exchange"
  statusQueueName: "notification_status"
  statusRoutingKey: "notification_status"

sender:
  pollInterval: "1s"
  batchSize: 10