// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protobuf/calendar_service.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_protobuf_calendar_service_proto protoreflect.FileDescriptor

const file_internal_protobuf_calendar_service_proto_rawDesc = "" +
	"\n" +
	"(internal/protobuf/calendar_service.proto\x12\bcalendar\x1a$internal/protobuf/create_event.proto\x1a$internal/protobuf/update_event.proto\x1a$internal/protobuf/delete_event.proto\x1a#internal/protobuf/list_events.proto2\x8f\x04\n" +
	"\x0fCalendarService\x12J\n" +
	"\vCreateEvent\x12\x1c.calendar.CreateEventRequest\x1a\x1d.calendar.CreateEventResponse\x12J\n" +
	"\vUpdateEvent\x12\x1c.calendar.UpdateEventRequest\x1a\x1d.calendar.UpdateEventResponse\x12J\n" +
	"\vDeleteEvent\x12\x1c.calendar.DeleteEventRequest\x1a\x1d.calendar.DeleteEventResponse\x12Y\n" +
	"\x10ListEventsForDay\x12!.calendar.ListEventsForDayRequest\x1a\".calendar.ListEventsForDayResponse\x12\\\n" +
	"\x11ListEventsForWeek\x12\".calendar.ListEventsForWeekRequest\x1a#.calendar.ListEventsForWeekResponse\x12_\n" +
	"\x12ListEventsForMonth\x12#.calendar.ListEventsForMonthRequest\x1a$.calendar.ListEventsForMonthResponseBQZOgithub.com/Evgeny2015/OTUS-Go-HomeWork/hw12_13_14_15_calendar/internal/protobufb\x06proto3"

var file_internal_protobuf_calendar_service_proto_goTypes = []any{
	(*CreateEventRequest)(nil),         // 0: calendar.CreateEventRequest
	(*UpdateEventRequest)(nil),         // 1: calendar.UpdateEventRequest
	(*DeleteEventRequest)(nil),         // 2: calendar.DeleteEventRequest
	(*ListEventsForDayRequest)(nil),    // 3: calendar.ListEventsForDayRequest
	(*ListEventsForWeekRequest)(nil),   // 4: calendar.ListEventsForWeekRequest
	(*ListEventsForMonthRequest)(nil),  // 5: calendar.ListEventsForMonthRequest
	(*CreateEventResponse)(nil),        // 6: calendar.CreateEventResponse
	(*UpdateEventResponse)(nil),        // 7: calendar.UpdateEventResponse
	(*DeleteEventResponse)(nil),        // 8: calendar.DeleteEventResponse
	(*ListEventsForDayResponse)(nil),   // 9: calendar.ListEventsForDayResponse
	(*ListEventsForWeekResponse)(nil),  // 10: calendar.ListEventsForWeekResponse
	(*ListEventsForMonthResponse)(nil), // 11: calendar.ListEventsForMonthResponse
}
var file_internal_protobuf_calendar_service_proto_depIdxs = []int32{
	0,  // 0: calendar.CalendarService.CreateEvent:input_type -> calendar.CreateEventRequest
	1,  // 1: calendar.CalendarService.UpdateEvent:input_type -> calendar.UpdateEventRequest
	2,  // 2: calendar.CalendarService.DeleteEvent:input_type -> calendar.DeleteEventRequest
	3,  // 3: calendar.CalendarService.ListEventsForDay:input_type -> calendar.ListEventsForDayRequest
	4,  // 4: calendar.CalendarService.ListEventsForWeek:input_type -> calendar.ListEventsForWeekRequest
	5,  // 5: calendar.CalendarService.ListEventsForMonth:input_type -> calendar.ListEventsForMonthRequest
	6,  // 6: calendar.CalendarService.CreateEvent:output_type -> calendar.CreateEventResponse
	7,  // 7: calendar.CalendarService.UpdateEvent:output_type -> calendar.UpdateEventResponse
	8,  // 8: calendar.CalendarService.DeleteEvent:output_type -> calendar.DeleteEventResponse
	9,  // 9: calendar.CalendarService.ListEventsForDay:output_type -> calendar.ListEventsForDayResponse
	10, // 10: calendar.CalendarService.ListEventsForWeek:output_type -> calendar.ListEventsForWeekResponse
	11, // 11: calendar.CalendarService.ListEventsForMonth:output_type -> calendar.ListEventsForMonthResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protobuf_calendar_service_proto_init() }
func file_internal_protobuf_calendar_service_proto_init() {
	if File_internal_protobuf_calendar_service_proto != nil {
		return
	}
	file_internal_protobuf_create_event_proto_init()
	file_internal_protobuf_update_event_proto_init()
	file_internal_protobuf_delete_event_proto_init()
	file_internal_protobuf_list_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_calendar_service_proto_rawDesc), len(file_internal_protobuf_calendar_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protobuf_calendar_service_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_calendar_service_proto_depIdxs,
	}.Build()
	File_internal_protobuf_calendar_service_proto = out.File
	file_internal_protobuf_calendar_service_proto_goTypes = nil
	file_internal_protobuf_calendar_service_proto_depIdxs = nil
}
