// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protobuf/delete_event.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeleteEvent
type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_internal_protobuf_delete_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_delete_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_delete_event_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_internal_protobuf_delete_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_delete_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_delete_event_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_protobuf_delete_event_proto protoreflect.FileDescriptor

const file_internal_protobuf_delete_event_proto_rawDesc = "" +
	"\n" +
	"$internal/protobuf/delete_event.proto\x12\bcalendar\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessBQZOgithub.com/Evgeny2015/OTUS-Go-HomeWork/hw12_13_14_15_calendar/internal/protobufb\x06proto3"

var (
	file_internal_protobuf_delete_event_proto_rawDescOnce sync.Once
	file_internal_protobuf_delete_event_proto_rawDescData []byte
)

func file_internal_protobuf_delete_event_proto_rawDescGZIP() []byte {
	file_internal_protobuf_delete_event_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_delete_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_delete_event_proto_rawDesc), len(file_internal_protobuf_delete_event_proto_rawDesc)))
	})
	return file_internal_protobuf_delete_event_proto_rawDescData
}

var file_internal_protobuf_delete_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protobuf_delete_event_proto_goTypes = []any{
	(*DeleteEventRequest)(nil),  // 0: calendar.DeleteEventRequest
	(*DeleteEventResponse)(nil), // 1: calendar.DeleteEventResponse
}
var file_internal_protobuf_delete_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protobuf_delete_event_proto_init() }
func file_internal_protobuf_delete_event_proto_init() {
	if File_internal_protobuf_delete_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_delete_event_proto_rawDesc), len(file_internal_protobuf_delete_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protobuf_delete_event_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_delete_event_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_delete_event_proto_msgTypes,
	}.Build()
	File_internal_protobuf_delete_event_proto = out.File
	file_internal_protobuf_delete_event_proto_goTypes = nil
	file_internal_protobuf_delete_event_proto_depIdxs = nil
}
