// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protobuf/event.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a calendar event
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DateTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotifyBefore  *durationpb.Duration   `protobuf:"bytes,7,opt,name=notify_before,json=notifyBefore,proto3" json:"notify_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_protobuf_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Event) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetNotifyBefore() *durationpb.Duration {
	if x != nil {
		return x.NotifyBefore
	}
	return nil
}

var File_internal_protobuf_event_proto protoreflect.FileDescriptor

const file_internal_protobuf_event_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/protobuf/event.proto\x12\bcalendar\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x98\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x127\n" +
	"\tdate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12>\n" +
	"\rnotify_before\x18\a \x01(\v2\x19.google.protobuf.DurationR\fnotifyBeforeBQZOgithub.com/Evgeny2015/OTUS-Go-HomeWork/hw12_13_14_15_calendar/internal/protobufb\x06proto3"

var (
	file_internal_protobuf_event_proto_rawDescOnce sync.Once
	file_internal_protobuf_event_proto_rawDescData []byte
)

func file_internal_protobuf_event_proto_rawDescGZIP() []byte {
	file_internal_protobuf_event_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_event_proto_rawDesc), len(file_internal_protobuf_event_proto_rawDesc)))
	})
	return file_internal_protobuf_event_proto_rawDescData
}

var file_internal_protobuf_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protobuf_event_proto_goTypes = []any{
	(*Event)(nil),                 // 0: calendar.Event
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
}
var file_internal_protobuf_event_proto_depIdxs = []int32{
	1, // 0: calendar.Event.date_time:type_name -> google.protobuf.Timestamp
	2, // 1: calendar.Event.duration:type_name -> google.protobuf.Duration
	2, // 2: calendar.Event.notify_before:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_protobuf_event_proto_init() }
func file_internal_protobuf_event_proto_init() {
	if File_internal_protobuf_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_event_proto_rawDesc), len(file_internal_protobuf_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protobuf_event_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_event_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_event_proto_msgTypes,
	}.Build()
	File_internal_protobuf_event_proto = out.File
	file_internal_protobuf_event_proto_goTypes = nil
	file_internal_protobuf_event_proto_depIdxs = nil
}
