// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protobuf/list_events.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListEventsForDay
type ListEventsForDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForDayRequest) Reset() {
	*x = ListEventsForDayRequest{}
	mi := &file_internal_protobuf_list_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForDayRequest) ProtoMessage() {}

func (x *ListEventsForDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_list_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForDayRequest.ProtoReflect.Descriptor instead.
func (*ListEventsForDayRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_list_events_proto_rawDescGZIP(), []int{0}
}

func (x *ListEventsForDayRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type ListEventsForDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForDayResponse) Reset() {
	*x = ListEventsForDayResponse{}
	mi := &file_internal_protobuf_list_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForDayResponse) ProtoMessage() {}

func (x *ListEventsForDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_list_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForDayResponse.ProtoReflect.Descriptor instead.
func (*ListEventsForDayResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_list_events_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsForDayResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// ListEventsForWeek
type ListEventsForWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartOfWeek   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_of_week,json=startOfWeek,proto3" json:"start_of_week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForWeekRequest) Reset() {
	*x = ListEventsForWeekRequest{}
	mi := &file_internal_protobuf_list_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForWeekRequest) ProtoMessage() {}

func (x *ListEventsForWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_list_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForWeekRequest.ProtoReflect.Descriptor instead.
func (*ListEventsForWeekRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_list_events_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsForWeekRequest) GetStartOfWeek() *timestamppb.Timestamp {
	if x != nil {
		return x.StartOfWeek
	}
	return nil
}

type ListEventsForWeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForWeekResponse) Reset() {
	*x = ListEventsForWeekResponse{}
	mi := &file_internal_protobuf_list_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForWeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForWeekResponse) ProtoMessage() {}

func (x *ListEventsForWeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_list_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForWeekResponse.ProtoReflect.Descriptor instead.
func (*ListEventsForWeekResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_list_events_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsForWeekResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// ListEventsForMonth
type ListEventsForMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartOfMonth  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_of_month,json=startOfMonth,proto3" json:"start_of_month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForMonthRequest) Reset() {
	*x = ListEventsForMonthRequest{}
	mi := &file_internal_protobuf_list_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForMonthRequest) ProtoMessage() {}

func (x *ListEventsForMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_list_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForMonthRequest.ProtoReflect.Descriptor instead.
func (*ListEventsForMonthRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_list_events_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsForMonthRequest) GetStartOfMonth() *timestamppb.Timestamp {
	if x != nil {
		return x.StartOfMonth
	}
	return nil
}

type ListEventsForMonthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForMonthResponse) Reset() {
	*x = ListEventsForMonthResponse{}
	mi := &file_internal_protobuf_list_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForMonthResponse) ProtoMessage() {}

func (x *ListEventsForMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_list_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForMonthResponse.ProtoReflect.Descriptor instead.
func (*ListEventsForMonthResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_list_events_proto_rawDescGZIP(), []int{5}
}

func (x *ListEventsForMonthResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_internal_protobuf_list_events_proto protoreflect.FileDescriptor

const file_internal_protobuf_list_events_proto_rawDesc = "" +
	"\n" +
	"#internal/protobuf/list_events.proto\x12\bcalendar\x1a\x1dinternal/protobuf/event.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\x17ListEventsForDayRequest\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"C\n" +
	"\x18ListEventsForDayResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"Z\n" +
	"\x18ListEventsForWeekRequest\x12>\n" +
	"\rstart_of_week\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vstartOfWeek\"D\n" +
	"\x19ListEventsForWeekResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"]\n" +
	"\x19ListEventsForMonthRequest\x12@\n" +
	"\x0estart_of_month\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fstartOfMonth\"E\n" +
	"\x1aListEventsForMonthResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06eventsBQZOgithub.com/Evgeny2015/OTUS-Go-HomeWork/hw12_13_14_15_calendar/internal/protobufb\x06proto3"

var (
	file_internal_protobuf_list_events_proto_rawDescOnce sync.Once
	file_internal_protobuf_list_events_proto_rawDescData []byte
)

func file_internal_protobuf_list_events_proto_rawDescGZIP() []byte {
	file_internal_protobuf_list_events_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_list_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_list_events_proto_rawDesc), len(file_internal_protobuf_list_events_proto_rawDesc)))
	})
	return file_internal_protobuf_list_events_proto_rawDescData
}

var file_internal_protobuf_list_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_protobuf_list_events_proto_goTypes = []any{
	(*ListEventsForDayRequest)(nil),    // 0: calendar.ListEventsForDayRequest
	(*ListEventsForDayResponse)(nil),   // 1: calendar.ListEventsForDayResponse
	(*ListEventsForWeekRequest)(nil),   // 2: calendar.ListEventsForWeekRequest
	(*ListEventsForWeekResponse)(nil),  // 3: calendar.ListEventsForWeekResponse
	(*ListEventsForMonthRequest)(nil),  // 4: calendar.ListEventsForMonthRequest
	(*ListEventsForMonthResponse)(nil), // 5: calendar.ListEventsForMonthResponse
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
	(*Event)(nil),                      // 7: calendar.Event
}
var file_internal_protobuf_list_events_proto_depIdxs = []int32{
	6, // 0: calendar.ListEventsForDayRequest.date:type_name -> google.protobuf.Timestamp
	7, // 1: calendar.ListEventsForDayResponse.events:type_name -> calendar.Event
	6, // 2: calendar.ListEventsForWeekRequest.start_of_week:type_name -> google.protobuf.Timestamp
	7, // 3: calendar.ListEventsForWeekResponse.events:type_name -> calendar.Event
	6, // 4: calendar.ListEventsForMonthRequest.start_of_month:type_name -> google.protobuf.Timestamp
	7, // 5: calendar.ListEventsForMonthResponse.events:type_name -> calendar.Event
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_protobuf_list_events_proto_init() }
func file_internal_protobuf_list_events_proto_init() {
	if File_internal_protobuf_list_events_proto != nil {
		return
	}
	file_internal_protobuf_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_list_events_proto_rawDesc), len(file_internal_protobuf_list_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protobuf_list_events_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_list_events_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_list_events_proto_msgTypes,
	}.Build()
	File_internal_protobuf_list_events_proto = out.File
	file_internal_protobuf_list_events_proto_goTypes = nil
	file_internal_protobuf_list_events_proto_depIdxs = nil
}
