// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protobuf/update_event.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateEvent
type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_internal_protobuf_update_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_update_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_update_event_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_internal_protobuf_update_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protobuf_update_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_protobuf_update_event_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_internal_protobuf_update_event_proto protoreflect.FileDescriptor

const file_internal_protobuf_update_event_proto_rawDesc = "" +
	"\n" +
	"$internal/protobuf/update_event.proto\x12\bcalendar\x1a\x1dinternal/protobuf/event.proto\"K\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x05event\x18\x02 \x01(\v2\x0f.calendar.EventR\x05event\"<\n" +
	"\x13UpdateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05eventBQZOgithub.com/Evgeny2015/OTUS-Go-HomeWork/hw12_13_14_15_calendar/internal/protobufb\x06proto3"

var (
	file_internal_protobuf_update_event_proto_rawDescOnce sync.Once
	file_internal_protobuf_update_event_proto_rawDescData []byte
)

func file_internal_protobuf_update_event_proto_rawDescGZIP() []byte {
	file_internal_protobuf_update_event_proto_rawDescOnce.Do(func() {
		file_internal_protobuf_update_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protobuf_update_event_proto_rawDesc), len(file_internal_protobuf_update_event_proto_rawDesc)))
	})
	return file_internal_protobuf_update_event_proto_rawDescData
}

var file_internal_protobuf_update_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protobuf_update_event_proto_goTypes = []any{
	(*UpdateEventRequest)(nil),  // 0: calendar.UpdateEventRequest
	(*UpdateEventResponse)(nil), // 1: calendar.UpdateEventResponse
	(*Event)(nil),               // 2: calendar.Event
}
var file_internal_protobuf_update_event_proto_depIdxs = []int32{
	2, // 0: calendar.UpdateEventRequest.event:type_name -> calendar.Event
	2, // 1: calendar.UpdateEventResponse.event:type_name -> calendar.Event
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protobuf_update_event_proto_init() }
func file_internal_protobuf_update_event_proto_init() {
	if File_internal_protobuf_update_event_proto != nil {
		return
	}
	file_internal_protobuf_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protobuf_update_event_proto_rawDesc), len(file_internal_protobuf_update_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protobuf_update_event_proto_goTypes,
		DependencyIndexes: file_internal_protobuf_update_event_proto_depIdxs,
		MessageInfos:      file_internal_protobuf_update_event_proto_msgTypes,
	}.Build()
	File_internal_protobuf_update_event_proto = out.File
	file_internal_protobuf_update_event_proto_goTypes = nil
	file_internal_protobuf_update_event_proto_depIdxs = nil
}
